version: '3.8'
services:
  postgres:
    image: postgres:16.9
    container_name: springcatalog_db
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
#      - pg_data:/var/lib/postgresql/data
      - ./src/main/resources/:/docker-entrypoint-initdb.d/
volumes:
  pg_data:
