version: '3.8'

services:
  postgres:
    image: postgres:16.9
    container_name: springcatalog_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      DEBUG: true
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
