version: '3.8'
services:
  postgres:
    image: postgres:16.9
    container_name: springcatalog_db
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: catalog_db         # базовая БД для инициализации — не критично
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d keycloak"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      # - pg_data:/var/lib/postgresql/data
      - ./src/test/resources/:/docker-entrypoint-initdb.d/

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    depends_on:
      postgres:
        condition: service_healthy
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL_HOST: postgres        # <-- ВАЖНО: имя сервиса Postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    volumes:
      - kcdata:/opt/keycloak/data

volumes:
  pg_data:
  kcdata:
